{% set name = "openlineage-airflow" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 054c29c6636e074af569db9a677d6eb5ffb8de54b8cfe64450fdf10134037fda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - attrs >=20.3
    - requests >=2.20.0
    - openlineage-integration-common =={{ version }}
    - openlineage-python =={{ version }}
  run_constrained:
    - apache-airflow >=2.3

test:
  imports:
    - openlineage.airflow
    - openlineage.airflow.extractors
    - openlineage.lineage_backend
  commands:
    - pip check
  requires:
    - pip
    - apache-airflow >=2.3

about:
  summary: OpenLineage integration with Airflow
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://openlineage.io/docs/integrations/airflow/
  dev_url: https://github.com/OpenLineage/OpenLineage/tree/main/integration/airflow

extra:
  recipe-maintainers:
    - rxm7706
