{% set name = "openlineage-airflow" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a53756422baa7fac692a9ae3e1cb7f428e60792f5b84b977df302d285395fa8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - attrs >=20.3
    - requests >=2.20.0
    - openlineage-integration-common =={{ version }}
    - openlineage-python =={{ version }}
  run_constrained:
    - apache-airflow >=2.3

test:
  imports:
    - openlineage.airflow
    - openlineage.airflow.extractors
    - openlineage.lineage_backend
  commands:
    - pip check
  requires:
    - pip
    - apache-airflow >=2.3

about:
  summary: OpenLineage integration with Airflow
  home: https://github.com/OpenLineage/OpenLineage
  description: "Starting from Airflow version 2.7.0 OpenLineage integration is included in Airflow repository as a provider. The apache-airflow-providers-openlineage package significantly ease lineage tracking in Airflow, ensuring stability by embedding the functionality directly into each provider and simplifying the process
    for users to select and manage lineage collection consumers.As a result, starting from Airflow 2.7.0 one should use the native Airflow Openlineage provider package."
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://openlineage.io/docs/integrations/airflow/
  dev_url: https://github.com/OpenLineage/OpenLineage/tree/main/integration/airflow

extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-integration-common
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
